hcss_blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, FileField
from wtforms.validators import DataRequired
from flask_wtf.file import FileField, FileAllowed
from flask_ckeditor import CKEditorField


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    # content = TextAreaField('Content', validators=[DataRequired()])
    content = CKEditorField('Content')
    post_photo = FileField('Post Picture', validators=[FileAllowed(['jpg', 'jpeg', 'png'])])
    tags = StringField('Tags')
    submit = SubmitField('Submit Post')

hcss_blog/admin/routes.py
from flask import Blueprint, render_template, redirect, url_for, abort, flash, request
from hcss_blog.models import User, Post
from hcss_blog import db
from hcss_blog.admin.forms import AuthorizeUserForm
from flask_login import current_user, login_required
from hcss_blog.admin.utils import send_user_authorization_email

admin = Blueprint('admin', __name__)

@admin.before_request
def before_request():
    if request.is_secure:
        return

    url = request.url
    if request.url.startswith('http://'):
        url = request.url.replace('http', 'https', 1)
    elif not 'https://' in url:
        url = f"https://{request.url}"

    return redirect(url, code=301)

@login_required
@admin.route('/admin', methods=['GET', 'POST'])
def admin_page():
    if not current_user.is_authenticated:
        abort(403)
    if current_user.role != 'admin':
        abort(403)
    users = User.query.filter_by(status='pending').order_by(User.username.asc()).all()
    posts = Post.query.filter_by(status='pending').order_by(Post.date_posted.desc()).all()
    all_users = User.query.filter(User.status!='pending').order_by(User.username.asc()).all()
    all_posts = Post.query.filter(Post.status!='pending').order_by(Post.date_posted.desc()).all()
    return render_template('admin.html', title='Admin', all_users=all_users,
                            all_posts=all_posts, users=users, posts=posts)


@login_required
@admin.route('/admin/view_user/<string:user_id>', methods=['GET', 'POST'])
def authorize_user(user_id):
    if not current_user.is_authenticated:
        return redirect(url_for('users.login'))
    if current_user.role != 'admin':
        abort(403)
    user = User.query.filter_by(id=user_id).first()
    form = AuthorizeUserForm()
    form.username.data = user.username
    form.email.data = user.email

    if form.validate_on_submit():
        user.role = form.account_role.data
        user.status = form.status.data
        db.session.commit()
        send_user_authorization_email(user)
        flash('User information is updated!', 'success')
        return redirect(url_for('admin.admin_page'))

    return render_template('approve_user.html', form=form, user=user)

hcss_blog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint, current_app)
from flask_login import current_user, login_required
from hcss_blog import db
from hcss_blog.models import Post, User
from hcss_blog.posts.forms import PostForm
from hcss_blog.posts.utils import month_range, send_new_post_email, send_new_post_notification
from hcss_blog.utils import save_picture, delete_picture
import os

posts = Blueprint('posts', __name__)

@posts.before_request
def before_request():
    if request.is_secure:
        return

    url = request.url
    if request.url.startswith('http://'):
        url = request.url.replace('http', 'https', 1)
    elif not 'https://' in url:
        url = f"https://{request.url}"

    return redirect(url, code=301)

def tags():
    return get_all_tags()

@posts.route('/student-posts')
def student_posts():
    page = request.args.get('page', 1, type=int)
    posts  = Post.query.join(User).filter(User.role == 'student')\
                        .order_by(Post.date_posted.desc())\
                        .paginate(page=page, per_page=6)
    return render_template('posts.html', posts=posts, title='Student Posts')

@posts.route('/staff_posts')
def staff_posts():
    page = request.args.get('page', 1, type=int)
    posts  = Post.query.join(User).filter(((User.role == 'staff') | (User.role == 'admin')) & (Post.status == 'approved'))\
                        .order_by(Post.date_posted.desc())\
                        .paginate(page=page, per_page=6)
    return render_template('posts.html', posts=posts, title='Staff Posts')

@posts.route("/datetags/<string:date_tag>")
def by_date_tag(date_tag):
    page = request.args.get('page', 1, type=int)
    first_day, last_day = month_range(date_tag)
    posts = Post.query.filter((Post.date_posted >= first_day) \
                             & (Post.date_posted < last_day )\
                             & (Post.status == 'approved'))\
                        .order_by(Post.date_posted.desc())\
                        .paginate(page=page, per_page=6)
    return render_template('datetags.html', posts=posts, date_tag=date_tag)

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        if form.post_photo.data:
            photo = save_picture(form.post_photo.data)
        else:
            photo = 'no_picture.jpg'

        post = Post(title=form.title.data, content=form.content.data, tags=form.tags.data,
                    post_photo=photo, user_id=current_user.id)
        if (current_user.role == 'admin'):
            post.status = 'approved'
        db.session.add(post)
        db.session.commit()
        send_new_post_email(post)
        flash('Post is created successfully', 'info')
        return redirect(url_for('main.index'))
    return render_template('create_post.html', form=form, title='Create Post')


@posts.route("/post/<int:post_id>",methods=['GET', 'POST'] )
def post(post_id):
    post = Post.query.get_or_404(post_id)
    author = post.author
    posts_by_author = Post.query.join(User).filter((User.id == author.id) & (Post.id != post.id))\
                                .order_by(Post.date_posted.desc()).limit(5)
    if request.method == 'POST':
        if request.form['submit_button'] == 'Approve':
            post.status = 'approved'
            db.session.commit()
            send_new_post_notification(post)
            flash('Post is available for public view now!', 'success')
            return redirect(url_for('admin.admin_page'))
        elif request.form['submit_button'] == 'Reject':
            post.status = 'rejected'
            db.session.commit()
            flash('Post will not be available for public view!', 'warning')
            return redirect(url_for('admin.admin_page'))
        elif request.form['submit_button'] == 'Delete':
            db.session.delete(post)
            db.session.commit()
            old_pic = post.post_photo
            if (old_pic != 'no_picture.jpg') and ('amazonaws' in old_pic):
                try:
                    delete_picture(old_pic)
                except:
                    flash('Associated picture not found!', 'warning')
            flash('Post is deleted from the blog successfully', 'success')
            return redirect(url_for('admin.admin_page'))
    elif request.method == 'GET':
        return render_template('post.html', title=post.title, post=post, posts_by_author=posts_by_author)

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if not (post.author == current_user or current_user.role == 'admin'):
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.tags = form.tags.data
        if form.post_photo.data:
            old_pic = post.post_photo
            photo = save_picture(form.post_photo.data)
            post.post_photo = photo
            if (old_pic != 'no_picture.jpg') and ('amazonaws' in old_pic):
                try:
                    delete_picture(old_pic)
                except:
                    flash('Associated picture not found!', 'warning')
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
        form.tags.data = post.tags
    return render_template('create_post.html', title='Update Post',
                        form=form, legend='Update Post')

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if not (post.author == current_user or current_user.role == 'admin'):
        abort(403)
    db.session.delete(post)
    db.session.commit()
    old_pic = post.post_photo
    if (old_pic != 'no_picture.jpg') and ('amazonaws' in old_pic):
        try:
            delete_picture(old_pic)
        except:
            flash('Associated picture not found!', 'warning')
    flash('Post is deleted from the blog successfully', 'success')
    return redirect(url_for('main.index'))

@posts.route('/tags/<string:tag>')
def tag_posts(tag):
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter((Post.tags.contains(tag)) & (Post.status=='approved'))\
                    .order_by(Post.date_posted.desc())\
                    .paginate(page=page, per_page=6)
    return render_template('tags.html', posts=posts, tag=tag, title=tag.title())

hcss_blog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, current_app
from flask_login import login_user, current_user, logout_user, login_required
from hcss_blog import db, bcrypt
from hcss_blog.models import User, Post
from hcss_blog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from hcss_blog.users.utils import send_reset_email, notify_registration
from hcss_blog.utils import save_picture, delete_picture
import os

users = Blueprint('users', __name__)

@users.before_request
def before_request():
    if request.is_secure:
        return

    url = request.url
    if request.url.startswith('http://'):
        url = request.url.replace('http', 'https', 1)
    elif not 'https://' in url:
        url = f"https://{request.url}"

    return redirect(url, code=301)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            if user.status=='approved':
                login_user(user, remember=form.remember.data)
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('main.index'))
            else:
                flash('Your registration request is in progress for approval', 'info')
                # return redirect(url_for('main.index'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        #initial user
        # user = User(
        #         username=form.username.data,
        #         email=form.email.data,
        #         password=hashed_password,
        #         role = 'admin',
        #         status = 'approved'
        #         )
        db.session.add(user)
        db.session.commit()
        notify_registration(user)
        flash('Your account has been submitted for approval!', 'success')
        return redirect(url_for('main.index'))
    return render_template('register.html', title='Register', form=form)


@users.route("/logout")
def logout():
    logout_user()
    flash('You logged out successfully!', 'success')
    return redirect(url_for('main.index'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    form2 = ResetPasswordForm()
    if form.validate_on_submit():
        if form.picture.data:
            old_pic = current_user.image_file
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
            if 'amazonaws' in old_pic:
                delete_picture(old_pic)
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    if form2.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form2.password.data).decode('utf-8')
        current_user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    if current_user.image_file == 'default-avatar.png':
        image_file = url_for('static', filename= 'profile_pics/'+ current_user.image_file)
    else:
        image_file = current_user.image_file

    post_num = len(Post.query.filter_by(user_id=current_user.id).all())
    return render_template('account.html', title='Account', image_file=image_file, form=form, post_num=post_num, form2=form2)



@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter((Post.author==user) & (Post.status == 'approved'))\
            .order_by(Post.date_posted.desc())\
            .paginate(page=page, per_page=6)
    return render_template('user_posts.html', posts=posts, user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! Please log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

hcss_blog/templates/approve_user.html
{% extends "layout.html" %}

{% block content %}

<div class="card col-lg-12">
<div class="card-body">
<form method="POST">
  {{ form.hidden_tag() }}
  <div class="form-group">
    <h5><strong>{{form.username.label()}}</strong></h5>
    {{form.username(class="form-control", readonly=true)}}
  </div>
  <div class="form-group">
    <h5><strong>{{form.email.label()}}</strong></h5>
    {{form.email(class="form-control", readonly=true)}}
  </div>
  <div class="form-group">
    <h5><strong>{{form.account_role.label}}</strong></h5>
    {{form.account_role(class="form-control")}}
  </div>
  <div class="form-group">
    <h5><strong>{{form.status.label}}</strong></h5>
    {{form.status(class="form-control")}}
  </div>
    {{form.submit(class="btn btn-outline-primary")}}
</form>
</div>
</div>

{% endblock %}

hcss_blog/templates/index.html
{% extends "layout.html" %}

{% block main %}
<div class="col-12">

<!--- Image Slider -->
<div id="slides" class="carousel slide" data-ride="carousel">
	<ul class="carousel-indicators">
		<li data-target="#slides" data-slide-to="0" class="active"></li>
		<li data-target="#slides" data-slide-to="1"></li>
		<li data-target="#slides" data-slide-to="2"></li>
	</ul>
	<div class="carousel-inner">
		<div class="carousel-item active">
			<img src="{{url_for('static', filename='images/hcss2.jpg')}}">
			<div class="carousel-caption">
				<h1 class="display-2">HCSS BLOG</h1>
				<h3>A Blog by HCSS Staff and Students</h3>
				<a href="https://hampdencharter.org/" target="_blank" rel="noopener noreferrer">
					<button type="button" class="btn btn-outline-light btn-lg">School Website</button>
				</a>
			</div>
		</div>
		<div class="carousel-item">
			<img src="{{url_for('static', filename='images/hcss1.jpg')}}">
		</div>
		<div class="carousel-item">
			<img src="{{url_for('static', filename='images/hcss3.jpg')}}">
		</div>
	</div>
	<a class="carousel-control-prev" href="#slides" role="button" data-slide="prev">
		<span class="carousel-control-prev-icon" aria-hidden="true"></span>
		<span class="sr-only">Previous</span>
	</a>
	<a class="carousel-control-next" href="#slides" role="button" data-slide="next">
		<span class="carousel-control-next-icon" aria-hidden="true"></span>
		<span class="sr-only">Next</span>
	</a>
</div>


<!--- Jumbotron -->
<div class="jumbotron">
	<div class="container">
	<div class="row">
	<div class="col-md-6">
		<span>
			<br>
		<h5>
			The Hampden Charter School of Science is a top-ranking tuition-free college preparatory school founded in 2009. The mission of the HCSS is to provide a college preparatory-focused education to the youth of every race and ethnic group in Western Massachusetts.
		</h5>
		</span>
	</div>
	<div class="col-md-6 jumbotron-inner">
		<div class="">
			<img src="{{url_for('static', filename='images/circles-HAMPDEN-1.png')}}" alt="">
		</div>
		<div class="">
			<a href="https://hampdencharter.org/" target="_blank" rel="noopener noreferrer"><button class="btn btn-outline-secondary btn-lg">Visit HCSS Website</button></a>
	</div>
</div>
	</div>
</div>
</div>
</div>

{% endblock main %}

{% block content %}
	{% if posts.page == 1 %}

		<!--- Latest from Blog -->
    <div class="container padding">
    <div class="row welcome text-center">
    	<div class="col-12">
    		<h1 class="display-4">Latest From HCSS Blog</h1>
    	</div>
    	<hr>
    </div>
    </div>
	{% endif %}

		<!--- Cards -->
		<div class="container padding">
		<div class="row">
		{% if posts.items %}
		{% for post in posts.items %}
			<div class="col-md-6">
				<div class="card border-light">
	        <div class="card-body">
	          <div class="">
	            <a href="{{url_for('users.user_posts', username=post.author.username)}}">
	              <img class="rounded-circle user-img" src="{{ post.author.image_file if 'aws' in post.author.image_file else url_for('static', filename='profile_pics/default-avatar.png')}}">
	            </a>
	            <h4 class="card-title"><strong>{{post.title}}</strong></h4>
	            <div class="padding">
	              {{post.date_posted.strftime('%b %d, %Y')}} by <a class="muted" href="{{url_for('users.user_posts', username=post.author.username)}}">{{post.author.username}}</a>
	            </div>
	          </div>
	          {% if (post.post_photo != '' and post.post_photo != 'no_picture.jpg') %}
		          <a href="{{url_for('posts.post', post_id=post.id)}}">
		            <img class="card-img-top" src="{{post.post_photo if 'aws' in post.post_photo else url_for('static', filename='images/'+ post.post_photo)}}">
		          </a>
		          <br><br>
	          {% endif %}
	          <p class="card-text">{{post.content  | striptags | truncate(200)}}</p>
	          <a href="{{url_for('posts.post', post_id=post.id)}}" class=""><button class="btn btn-outline-secondary">Continue Reading</button></a>
	        </div>
	      </div>
			</div>
		{% endfor %}
		{% else %}
			<div class="container">
				<h4>
					Coming soon! Please check back later.
				</h4>
			</div>
		{% endif %}
			</div>
		</div>

			<div class="col-6">
				<a href="{{url_for('posts.staff_posts')}}"><button class="btn btn-outline-info btn-lg btn-block">Staff Posts</button></a>
			</div>
			<div class="col-6">
				<a href="{{url_for('posts.student_posts')}}"><button type="button" class="btn btn-outline-info btn-lg btn-block">Student Posts</button></a>
			</div>
{% endblock %}

{% block extra %}
{% if posts.page == 1 %}
<figure>
	<div class="fixed-wrap">
		<div id="fixed">
		</div>
	</div>
</figure>
{% endif %}
{% endblock extra%}

hcss_blog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	{% if title %}
     <title>HCSS Blog - {{title}}</title>
  {% else %}
     <title>HCSS Blog</title>
  {% endif %}

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script> -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
	<link href="{{url_for('static', filename='style.css')}}" rel="stylesheet">
	{% block head %}

	{% endblock head %}
	<!-- <link href="{{url_for('static', filename = 'floating-labels.css') }}" rel="stylesheet"> -->
</head>
<body>

<!-- <nav class="navbar navbar-expand-lg navbar-dark sticky-top" style="background-color: #003366;"> -->
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
	<div class="container">
		<a class="navbar-brand" href="{{url_for('main.index')}}"><img src="{{url_for('static', filename='images/hcss_logo.png')}}" height=50 width=50></a>
		<a class="navbar-brand" href="{{url_for('main.index')}}"><strong>HCSS blog</strong></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-Responsive">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse " id="navbar-Responsive">
			<ul class="navbar-nav">
				<li class="nav-item active">
					<a class="nav-link" href="{{url_for('main.index')}}">Home</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{url_for('posts.staff_posts')}}">Staff Posts</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{url_for('posts.student_posts')}}">Student Posts</a>
				</li>
			</ul>
			<ul class="navbar-nav ml-auto">
				{% if current_user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link" href="{{url_for('posts.new_post')}}">New Post</a>
					</li>
					{% if current_user.role == 'admin' %}
						<li class="nav-item">
							<a class="nav-link" href="{{url_for('admin.admin_page')}}">Admin</a>
						</li>
					{% endif %}
					<li class="nav-item">
						<a class="nav-link" href="{{url_for('users.account')}}">Account</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{url_for('users.logout')}}">Logout</a>
					</li>
				{% else %}
					<li class="nav-item">
						<a class="nav-link" href="#contact">Contact</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{url_for('users.register')}}">Register</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{url_for('users.login')}}">Login</a>
					</li>
				{% endif %}
			</ul>
		</div>
	</div>
</nav>
<div class="row">
<div class="container">
	{% with messages = get_flashed_messages(with_categories=true) %}
		{% if messages %}
			{% for category, message in messages %}
				<div class="alert alert-{{ category }} alert-dismissible fade show">
					{{message}}
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
			{% endfor %}
		{% endif %}
	{% endwith %}

	{% block main %}
	{% endblock main%}
</div>
</div>

<main class="container">
	<div class="row">
    <div class="col-lg-9">
			<div class="row">
        {% block content %}

        {% endblock %}
      </div>
    </div>
    <div class="col-lg-3 ml-auto">
			<aside class="sidebar">
				<div class="card border-light mb-4">
					<div class="card-body">
						<h4 class="card-title"><strong>About</strong></h4>
						<hr>
						<p class="card-text">The mission of the HCSS is to provide a college preparatory-focused education to the youth of every race and ethnic group in Western Massachusetts.</p>
						<p>Visit school <a a target="_blank" rel="noopener noreferrer" href="https://hampdencharter.org/">website</a> to get more information.</p>
					</div>
				</div>
			</aside>
			<aside class="sidebar">
				<div class="card border-light mb-4">
					<div class="card-body">
						<h4 class="card-title"><strong>Tags</strong></h4>
						<hr>
						{% for tag in all_tags %}
							<a class="btn btn-light btn-sm mb-1" href="{{url_for('posts.tag_posts', tag=tag)}}">{{tag}}</a>
						{% endfor %}
					</div>
				</div>
				<div class="card border-light mb-4">
					<div class="card-body">
						<h4 class="card-title"><strong>Latest Posts</strong></h4>
						<hr>
						{% for latest_post in latest_posts %}
							<h6><strong>{{latest_post.title}}</strong></h6>
							<a href="{{url_for('posts.post', post_id=latest_post.id)}}" class="d-inline-block mt-3">
								<img class="card-img" src="{{ latest_post.post_photo if 'aws' in latest_post.post_photo else url_for('static', filename='images/'+latest_post.post_photo)}}"/>
							</a>
							<br><br>
						{% endfor %}
						<!-- <h5>Rigor and Achievement</h5>
						<a href="#" class="d-inline-block mt-3">
							<img class="card-img" src="{{url_for('static', filename='images/hcss1.jpg')}}" alt="" />
						</a>
						<br><br>
						<h5>Brain and Learning</h5>
						<a href="#" class="d-inline-block mt-3">
							<img class="card-img" src="{{url_for('static', filename='images/science-lab.jpg')}}" alt="" />
						</a> -->
					</div>
				</div>
		<div class="card border-light mb-4">
				<div class="card-body">
				<h4 class="card-title"><strong>Archives</strong></h4>
				<hr>
						{% for month in last_months %}
							<a class="btn btn-light btn-sm mb-1" href="{{url_for('posts.by_date_tag', date_tag=month)}}">{{month}}</a>
						{% endfor %}
	      </div>
			</div>
			</aside>
		</div>
	</div>
</main>

{% block extra %}
{% endblock extra%}
<!--- Connect -->
<div class="container-fluid padding" id="contact">
 <div class="row text-center">
	<!-- <div class="col-12">
		<h2 class="display-4">Connect</h2>
		<hr class="light">
	</div> -->
	<div class="col-12 social padding">
		<a target="_blank" rel="noopener noreferrer" href="https://www.facebook.com/HampdenCharter/"><i class="fab fa-facebook"></i></a>
		<a target="_blank" rel="noopener noreferrer" href="https://twitter.com/hampdencharter"><i class="fab fa-twitter"></i></a>
		<!-- <a href="#"><i class="fab fa-google-plus-g"></i></a> -->
		<a target="_blank" rel="noopener noreferrer" href="https://www.instagram.com/hampdencharter/"><i class="fab fa-instagram"></i></a>
		<a target="_blank" rel="noopener noreferrer" href="https://www.youtube.com/channel/UCM5nysPjHOOzI8xcPVFk7-g"><i class="fab fa-youtube"></i></a>
	</div>
</div>
</div>
<!--- Footer -->
<footer id="footer">
	<div class="container-fluid padding">
	<div class="row text-center">
		<div class="col-md-4">
			<img src="https://hampdencharter.org/wp-content/uploads/2019/11/logo-footer.png">
		</div>
		<div class="col-md-4">
			<hr class="light">
			<h5>HCSS East</h5>
			<hr class="light">
			<p>20 Johnson Rd. Chicopee, MA 01022</p>
			<p>Ph: (413) 593 9090</p>
			<p>Fax: (413) 294-2648</p>
			<p>info@hampdencharter.org</p>
		</div>
		<div class="col-md-4">
			<hr class="light">
			<h5>HCSS West</h5>
			<hr class="light">
			<p>511 Main St. West Springfield, MA 01089</p>
			<p>Ph: (413) 278-5450</p>
			<p>Fax: 9413) 278- 5387</p>
			<p>info@hampdencharter.org</p>
		</div>
		<div class="col-12">
			<hr class="light">
			<h5>&copy; Hampden Charter School of Science</h5>
		</div>
	</div>
	</div>
</footer>

</body>
</html>